version: "3.8"
services: 
  traefik:
    build: .
    ports:
    - 80:80
    - 8080:8080
    labels:
      traefik.enable: "true"
      traefik.http.routers.healthcheck.entrypoints: web
      traefik.http.routers.healthcheck.rule: Host(`localhost`)
      traefik.http.routers.healthcheck.service: api@internal
    command:
    - "--api.insecure=true"
    - "--providers.docker=true"
    - "--providers.docker.exposedbydefault=false"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro