version: "3.8"
services: 
  traefik:
    build: .
    ports:
    - 80:80
    - 8080:8080
    command:
    - "--api.insecure=true"
    - "--providers.docker=true"
    - "--providers.docker.exposedbydefault=false"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro